"""empty message

Revision ID: 4273cd31ddf6
Revises: 
Create Date: 2026-09-10 01:49:10.057247-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4273cd31ddf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pk')),
    sa.UniqueConstraint('email', name=op.f('users_email_uq')),
    sa.UniqueConstraint('username', name=op.f('users_username_uq'))
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('full_name', postgresql.CITEXT(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('patients_users_user_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pk'))
    )
    op.create_index(op.f('patients_full_name_ix'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('patients_user_id_ix'), 'patients', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('individual_pd', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('individual_add', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_settings_users_user_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_settings_pk')),
    sa.UniqueConstraint('user_id', name=op.f('user_settings_user_id_uq'))
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('sphere_od', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sphere_os', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cylinder_od', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cylinder_os', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('axis_od', sa.Integer(), nullable=True),
    sa.Column('axis_os', sa.Integer(), nullable=True),
    sa.Column('pd_od', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('pd_os', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('add_od', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('add_os', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image', sqlalchemy_file.types.ImageField(none_as_null=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('add_od >= 0', name='check_add_od'),
    sa.CheckConstraint('add_os >= 0', name='check_add_os'),
    sa.CheckConstraint('axis_od BETWEEN 0 AND 180', name='check_axis_od'),
    sa.CheckConstraint('axis_os BETWEEN 0 AND 180', name='check_axis_os'),
    sa.CheckConstraint('pd_od >= 0', name='check_pd_od'),
    sa.CheckConstraint('pd_os >= 0', name='check_pd_os'),
    sa.CheckConstraint('sphere_od IS NOT NULL OR \n            sphere_os IS NOT NULL OR \n            cylinder_od IS NOT NULL OR \n            cylinder_os IS NOT NULL OR \n            axis_od IS NOT NULL OR \n            axis_os IS NOT NULL OR \n            add_od IS NOT NULL OR \n            add_os IS NOT NULL OR \n            pd_od IS NOT NULL OR \n            pd_os IS NOT NULL', name='check_at_least_one'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('prescriptions_patients_patient_id_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescriptions_pk'))
    )
    op.create_index(op.f('prescriptions_patient_id_ix'), 'prescriptions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('prescriptions_patient_id_ix'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_table('user_settings')
    op.drop_index(op.f('patients_user_id_ix'), table_name='patients')
    op.drop_index(op.f('patients_full_name_ix'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('users')
    # ### end Alembic commands ###
